---
abstract: 'get data from W3C SPARQL Protocol 1.0 servers'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
  - 'TOBYINK <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::11 version , CPAN::Meta::Converter version 2.140640'
keywords:
  - HTTP
  - Protocol
  - Query
  - RDF
  - REST
  - SPARQL
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RDF-Query-Client
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  RDF::Query::Client:
    file: lib/RDF/Query/Client.pm
    version: '0.113'
recommends:
  HTTP::LRDD: '0'
requires:
  Carp: '0'
  HTTP::Request: '0'
  LWP::UserAgent: '0'
  RDF::Trine: '0.133'
  Scalar::Util: '0'
  URI::Escape: '0'
  authority::shared: '0'
  namespace::clean: '0.20'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/RDF-Query-Client/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-Query-Client
  homepage: https://metacpan.org/release/RDF-Query-Client
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-rdf-query-client.git
version: '0.113'
x_contributors:
  - 'Jonas Smedegaard'
  - TOBYINK
